---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-ldap-image-pull-secret
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: 
      - name: ldap-image-pull-secret
target:
  kind: Deployment
  name: ldap-server
