---
apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  labels:
    app: ldap-service
spec:
  ports:
    - name: openldap-insecure-port
      port: 389
      targetPort: 389
      protocol: TCP
    - name: openldap-secure-port
      port: 636
      targetPort: 636
      protocol: TCP
  selector:
    app: ldap-server
